# Read the Docs configuration file for a Node.js project
# See https://docs.readthedocs.io/en/stable/config-file/v2.html for details

# Required
version: 2

# Specify the Node.js version you want to use
build:
  tools:
    nodejs: "20"  # Specify the Node.js version

# Install dependencies
install:
  - npm install               # Install project dependencies

# Define the build commands for your documentation
build:
  commands:
    - npm run build            # Build your Next.js project
    - npm run docs             # Command to build your documentation (ensure this exists in package.json)
